### ISSUE TITLE
Beachten des Flags zum ausblenden von Images

### ISSUE THREAD

**Issue by hamplr** [techdivision/import-product-media#35]
Aktuell besteht die Möglichkeit, über das Feld `additional_images` diverse Bilder zum Produkt zu importieren, sowie über das Feld `additionals_image_labels` die dazugehörigen Images Labels zu vergeben. Das darauf folgende Feld (`hide_from_product_page`) wird allerdings aktuell nicht beachtet. 

Hier sollte es möglich sein, eins oder mehrere Bilder, die innerhalb der `additional_images` angegeben sind, für das Produkt im Bezug auf einen bestimmten Store, als _hidden_ zu markieren.

**Comment by wagnert** [comment]
Has been released with version 3.5.0/2.6.0.
